# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PoolBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoolBuddy
pod 'Alamofire', '~> 4.5'
pod 'SwiftWebVC', '~> 0.4'
end
